### ISSUE TITLE
h2o4gpu

### ISSUE THREAD

**Issue by jonbaer** [gpuopenanalytics/demo-docker#12]
Where can I find this python package?

ENV H2O4GPU_WHL="h2o4gpu-0.0.3-py2.py3-none-any.whl"

**Comment by datametrician** [comment]
Hi @jonbaer, this will be officially released in a few days.

**Comment by wamsiv** [comment]
@jonbaer If you are looking for a py35 version of `h2o4gpu` you can download it from here:
https://s3.amazonaws.com/artifacts.h2o.ai/releases/bleeding-edge/ai/h2o/h2o4gpu/0.0.4/h2o4gpu-0.0.4-py35-none-any.whl

**Comment by michael-balint** [comment]
Latest versions are listed in the h2o4gpu github repo README: https://github.com/h2oai/h2o4gpu
