### ISSUE TITLE
Build failure from "docker build -t goai/demo:latest ./demo"

### ISSUE THREAD

**Issue by a-agrz** [gpuopenanalytics/demo-docker#20]
Hi !
I was able to execute the first command "docker build -t goai/base:latest ./base" without any problems
but I got this errors from the second one "docker build -t goai/demo:latest ./demo":

[aguerzaa@naboo15 (NABOO) notebook-demo-docker]$ docker build -t cudf:latest ./demo
Sending build context to Docker daemon  11.85MB
Step 1/42 : FROM goai/base:latest
 ---> d2375a936579
Step 2/42 : ENV PYGDF_CONDA_ENV=pygdf_examples
 ---> Using cache
 ---> 78e3b1de3c89
Step 3/42 : ENV http_proxy 'http://129.183.4.8:8080'
 ---> Using cache
 ---> d27a67580071
Step 4/42 : ENV https_proxy 'http://129.183.4.8:8080'
 ---> Using cache
 ---> a1ab2ea44146
Step 5/42 : ENV HTTP_PROXY 'http://129.183.4.8:8080'
 ---> Using cache
 ---> 44e57b2584a3
Step 6/42 : ENV HTTPS_PROXY 'http://129.183.4.8:8080'
 ---> Using cache
 ---> 1e680529c432
Step 7/42 : USER appuser
 ---> Using cache
 ---> 42f86fbf3053
Step 8/42 : RUN mkdir data
 ---> Using cache
 ---> 56c65336ce7c
Step 9/42 : RUN wget -nv http://archive.ics.uci.edu/ml/machine-learning-databases/00344/Activity%20recognition%20exp.zip -O "data/Activity recognition exp.zip"
 ---> Using cache
 ---> 7076547181f1
Step 10/42 : ENV MAPD_FILE="mapd-os-3.2.3dev-20170909-e7053e6-Linux-x86_64-open"
 ---> Using cache
 ---> 8097a59a0958
Step 11/42 : ADD https://mapd-core-os-builds.s3.amazonaws.com/${MAPD_FILE}.tar.gz ${MAPD_FILE}.tar.gz
Downloading [==================================================>]  83.12MB/83.12MB
 ---> Using cache
 ---> 377177b5e47a
Step 12/42 : USER root
 ---> Using cache
 ---> 903f541bed4f
Step 13/42 : RUN chown appuser ${MAPD_FILE}.tar.gz
 ---> Using cache
 ---> e8028594015e
Step 14/42 : USER appuser
 ---> Using cache
 ---> 25be426113b7
Step 15/42 : RUN tar -xvf ${MAPD_FILE}.tar.gz
 ---> Using cache
 ---> 0d5d7f23d7f7
Step 16/42 : RUN ln -s $MAPD_FILE ./mapd
 ---> Using cache
 ---> 7149d051f70c
Step 17/42 : ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/:/usr/local/nvidia/lib64/
 ---> Using cache
 ---> c72b566c1a88
Step 18/42 : RUN echo $LD_LIBRARY_PATH
 ---> Using cache
 ---> 44ac717e5157
Step 19/42 : RUN conda create -n $PYGDF_CONDA_ENV python=3.6
 ---> Using cache
 ---> f8af5f8bd1c7
Step 20/42 : RUN conda install -n $PYGDF_CONDA_ENV -y --no-update-deps -c numba -c defaults -c conda-forge -c gpuopenanalytics/label/dev pygdf=0.1.0a2=py36h01fc00e_29 numba=0.35 cudatoolkit=8
 ---> Running in 4642d2aa1ea3
Fetching package metadata ...............
Solving package specifications: .
Warning: 4 possible package resolutions (only showing differing packages):
  - conda-forge::boost-cpp-1.67.0-0, conda-forge::icu-58.2-hfc679d8_0
  - conda-forge::boost-cpp-1.67.0-0, conda-forge::icu-58.2-0
  - conda-forge::boost-cpp-1.67.0-h3a22d5f_0, conda-forge::icu-58.2-hfc679d8_0
  - conda-forge::boost-cpp-1.67.0-h3a22d5f_0, conda-forge::icu-58.2-0

Package plan for installation in environment /home/appuser/Miniconda3/envs/pygdf_examples:

The following NEW packages will be INSTALLED:

    arrow-cpp:       0.10.0-py36h70250a7_0   conda-forge               
    blas:            1.0-mkl                                           
    boost-cpp:       1.67.0-0                conda-forge               
    bzip2:           1.0.6-3                                           
    cffi:            1.10.0-py36_0                                     
    cudatoolkit:     8.0-3                   numba                     
    icu:             58.2-hfc679d8_0         conda-forge               
    libffi:          3.2.1-1                                           
    libgcc-ng:       7.2.0-hdf63c60_3        conda-forge               
    libgdf:          0.1.0a2.dev-405         gpuopenanalytics/label/dev
    libgdf_cffi:     0.1.0a2.dev-py36_405    gpuopenanalytics/label/dev
    libstdcxx-ng:    7.2.0-hdf63c60_3        conda-forge               
    llvmlite:        0.20.0-py36_0           numba                     
    mkl:             2017.0.3-0                                        
    numba:           0.35.0-np113py36_10     numba                     
    numpy:           1.13.1-py36_0                                     
    pandas:          0.20.3-py36_0                                     
    parquet-cpp:     1.5.0.pre-h83d4a3d_0    conda-forge               
    pyarrow:         0.10.0-py36hfc679d8_0   conda-forge               
    pycparser:       2.18-py36_0                                       
    pygdf:           0.1.0a2-py36h01fc00e_29 gpuopenanalytics/label/dev
    python-dateutil: 2.6.1-py36_0                                      
    pytz:            2017.2-py36_0                                     
    six:             1.10.0-py36_0                                     

blas-1.0-mkl.t 100% |###############################| Time: 0:00:00   2.09 MB/s
bzip2-1.0.6-3. 100% |###############################| Time: 0:00:00   1.94 MB/s
cudatoolkit-8. 100% |###############################| Time: 0:02:11   2.58 MB/s
libffi-3.2.1-1 100% |###############################| Time: 0:00:00   2.46 MB/s
libgcc-ng-7.2. 100% |###############################| Time: 0:00:02   2.58 MB/s
libstdcxx-ng-7 100% |###############################| Time: 0:00:01   2.06 MB/s
mkl-2017.0.3-0 100% |###############################| Time: 0:01:00   2.26 MB/s
icu-58.2-hfc67 100% |###############################| Time: 0:00:04   4.95 MB/s
boost-cpp-1.67 100% |###############################| Time: 0:00:03   6.80 MB/s
llvmlite-0.20. 100% |###############################| Time: 0:00:01   7.10 MB/s
numpy-1.13.1-p 100% |###############################| Time: 0:00:01   4.53 MB/s
pycparser-2.18 100% |###############################| Time: 0:00:00   8.08 MB/s
pytz-2017.2-py 100% |###############################| Time: 0:00:00  10.57 MB/s
six-1.10.0-py3 100% |###############################| Time: 0:00:00  20.49 MB/s
arrow-cpp-0.10 100% |###############################| Time: 0:00:00   4.83 MB/s
cffi-1.10.0-py 100% |###############################| Time: 0:00:00   3.25 MB/s
numba-0.35.0-n 100% |###############################| Time: 0:00:01   2.23 MB/s
python-dateuti 100% |###############################| Time: 0:00:00   1.42 MB/s
pandas-0.20.3- 100% |###############################| Time: 0:00:34 642.96 kB/s
parquet-cpp-1. 100% |###############################| Time: 0:00:02 491.66 kB/s
pyarrow-0.10.0 100% |###############################| Time: 0:00:02 713.06 kB/s
An unexpected error has occurred.###############    | Time: 0:00:06   1.08 MB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/appuser/Miniconda3  (writable)
    default environment : /home/appuser/Miniconda3
       envs directories : /home/appuser/Miniconda3/envs
                          /home/appuser/.conda/envs
          package cache : /home/appuser/Miniconda3/pkgs
                          /home/appuser/.conda/pkgs
           channel URLs : https://conda.anaconda.org/numba/linux-64
                          https://conda.anaconda.org/numba/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/gpuopenanalytics/label/dev/linux-64
                          https://conda.anaconda.org/gpuopenanalytics/label/dev/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Linux/3.10.0-693.17.1.el7.x86_64 debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000

`$ /home/appuser/Miniconda3/bin/conda install -n pygdf_examples -y --no-update-deps -c numba -c defaults -c conda-forge -c gpuopenanalytics/label/dev pygdf=0.1.0a2=py36h01fc00e_29 numba=0.35 cudatoolkit=8`

    Traceback (most recent call last):
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/plan.py", line 825, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 88, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 150, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 150, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Value for sha256 cannot be None.

libgdf-0.1.0a2 100% |###############################| Time: 0:00:06   1.14 MB/s
libgdf_cffi-0. 100% |###############################| Time: 0:00:00   6.42 MB/s
pygdf-0.1.0a2- 100% |###############################| Time: 0:00:00   2.89 MB/s
The command '/bin/bash -c conda install -n $PYGDF_CONDA_ENV -y --no-update-deps -c numba -c defaults -c conda-forge -c gpuopenanalytics/label/dev pygdf=0.1.0a2=py36h01fc00e_29 numba=0.35 cudatoolkit=8' returned a non-zero code: 1

PS: I have cuda-9.2 installed in my machine and all the GPU drivers are updated

Any help will be appreciated 

Best regards

aguerzaa

**Comment by datametrician** [comment]
This docker isn't supported anymore, please try the RAPIDS docker image https://hub.docker.com/r/rapidsai/rapidsai/

**Comment by a-agrz** [comment]
Thanks for the quiq replay.
I already installed it but does it contain all the datasets and code examples that are present in goai ?

**Comment by datametrician** [comment]
We need to move over the code examples and update them for the new APIs and functionality.
