### ISSUE TITLE
Docker build - CondaError MD5Mismatch

### ISSUE THREAD

**Issue by MM121z** [gpuopenanalytics/demo-docker#5]
docker build -t cudf:latest ./demo failed with error

CondaError: MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.continuum.io/pkgs/free/linux-64/numpy-1.12.1-py35_0.tar.bz2'.
  download saved to: /home/appuser/Miniconda3/pkgs/numpy-1.12.1-py35_0.tar.bz2
  expected md5 sum: fa544a6d6b3df642d335d76a05f761d8
  actual md5 sum: 099c631c5a2a814bf2099c1d0cdf7a00

**Comment by sklam** [comment]
The problem should have been fixed upstream for conda.  The build ran fine just now.
